version: '3'

services:
  epm-service:
    image: aws-lambda-r-runtime:latest
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - R_VERSION=3.5.2
      - PACKAGES=earth,futile.logger,genalg,polynom,segmented,stringr,config